version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: interview-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: interview_trainer
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_pass

    ports:
      - "5433:5432"

    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: